# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.vm.synced_folder '.', '/vagrant', type: 'nfs'

  config.vm.define "virtualbox" do |vb|
    vb.vm.hostname = "openedge"
    # Point OPENEDGE_BOX at the 18.04 build to test the legacy appliance.
    vb.vm.box = "file://" + (ENV["OPENEDGE_BOX"] || "builds/virtualbox-ubuntu2404.box")
    vb.vm.network :private_network, ip: "172.16.3.2"

    vb.vm.provider :virtualbox do |v|
      v.gui = false
      v.memory = 1024
      v.cpus = 1
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--ioapic", "on"]
    end

    vb.vm.provision "shell", inline: "docker --version && docker compose version && docker ps"
  end
end